### ISSUE TITLE
能不能改成c#的？

### ISSUE THREAD

**Issue by weituotian** [experdot/AutoPaint.NET#1]
看不懂啊，vb

**Comment by experdot** [comment]
有C#互转VB.NET的在线工具，适合翻译一般的代码：
- [Code Converter](http://converter.telerik.com/)
- [SnippetConverter](http://codeconverter.sharpdevelop.net/SnippetConverter.aspx)（比较好用但有时候不能访问）

**Comment by experdot** [comment]
考虑到C#相比VB.NET的社区影响力，我会在近期将类库改为C#项目，但WinForm项目的语言类型保持不变。

**Comment by experdot** [comment]
#5 有关重写计划请关注这个Issue
