### ISSUE TITLE
这项目很酷~~ 用什么工具打开？

### ISSUE THREAD

**Issue by weisuogou** [experdot/AutoPaint.NET#4]
vs studio？ 还是啥？ 有编译教程么？
跪谢大神

**Comment by experdot** [comment]
这是 VB.NET 项目，源码项目可以直接在 Visual Studio 中编译运行。
### See Also
- [安装 Visual Studio 2017](https://docs.microsoft.com/zh-cn/visualstudio/install/install-visual-studio)
- [Visual Studio 中的 Visual Basic 入门](https://docs.microsoft.com/zh-cn/visualstudio/ide/tutorial-visual-basic-console)

**Comment by weisuogou** [comment]
哈哈  多谢多谢。我先下了 编译下 研究研究。非常酷！  很想做那种线框画的  自动绘制效果 肯定非常棒

**Comment by weisuogou** [comment]
![1532156994 1](https://user-images.githubusercontent.com/13113888/43033180-3d92143e-8cf8-11e8-9b93-8ea66552f1f0.png)
效果非常酷。刚编译好，但是，您看我这个是一个非常简单的线框图，我想得到的效果就是 绘制，然后按照线条一条条去画。这个能用您这个项目修改么？ 或者是这种类似的是用啥 项目呢，就是这个车吧，一笔笔的画，一画就是一根线这种。多谢多谢(～￣▽￣～)

**Comment by experdot** [comment]
@weisuogou 这个是可以做到的，预览效果和实际绘制使用了两种算法。程序的最初用途是玩“你画我猜”游戏，你可以把程序移到 Windows 画板上，然后点击“Paint on screen”按钮。
### 演示视频
- [AutomaticDrawing-快速绘制黑白线条画!](https://www.bilibili.com/video/av11418289)

**Comment by weisuogou** [comment]
哈哈。 可以可以，。大神 您这个配乐 也有点厉害的。。  我先研究研究，能办就成路不错就ok！多谢多谢

**Comment by weisuogou** [comment]
我看您博客上有 c#版本的。github里没有找到(～￣▽￣～)  vb 有点看不懂哈，请问。哪里能找到c#  版的软件

**Comment by experdot** [comment]
没有 C# 版本

**Comment by weisuogou** [comment]
http://www.cnblogs.com/experdot/p/4494351.html  这个 博客也是您的呗，就是c# 只有算法部分是不

**Comment by experdot** [comment]
@weisuogou 是的，暂时没有用 C# 重写的计划。你可以用在线工具转换语言：[C# To VB.NET](http://converter.telerik.com)

**Comment by experdot** [comment]
#5 有关重写计划请关注这个 Issue
